const actionTypes = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SAVE_USER: 'SAVE_USER',
  STOP_LOADING: 'STOP_LOADING',
  SAVE_CSV_DATA: 'SAVE_CSV_DATA',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  SET_ACTIVE: 'SET_ACTIVE',
  SET_COUPON: 'SET_COUPON',
  SET_DISCOUNT: 'SET_DISCOUNT',
  SET_MODULE: 'SET_MODULE',
  SET_EDIT_MODE: 'SET_EDIT_MODE',
  SET_COUPON_ID: 'SET_COUPON_ID',
  ADD_COUPON: 'ADD_COUPON',
  LOAD_COUPONS: 'LOAD_COUPONS',
  UPDATE_COUPON: 'UPDATE_COUPON'
};

export default actionTypes;
